### ISSUE TITLE
Refresh token on the client-side

### ISSUE THREAD

**Issue by zatsepinvl** [aws-samples/amazon-cognito-passwordless-email-auth#15]
I have run this example and noted that refresh token is saved in web localStorage after login.

According the [auth0 documentation](https://auth0.com/docs/tokens/refresh-token/current#restrictions-on-refresh-token-usage):

> A Single-Page Application (normally implementing Implicit Flow) should not ever receive a Refresh Token. A Refresh Token is essentially a user credential that allows a user to remain authenticated indefinitely. This sensitive information should be stored securely and not exposed client-side in a browser.

So, is it secure to have a refresh token on the client?

**Comment by ottokruse** [comment]
Well, I guess the question is, is it secure enough in your context?

Auth0 is playing it safe. Security must be balanced with usability. This balance is different for every app, because it depends on the specific things the app is doing. Without a refresh token, users would need to sign-in again after an hour.

If your app is sensitive enough, you might indeed follow Auth0's advice and not store the refresh token. You can e.g. override the Auth storage object to achieve this.

**Comment by abiro** [comment]
Cognito supports invalidating refresh tokens with the [GlobalSignOut](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GlobalSignOut.html) API call, so I don't think this is an issue.

**Comment by deepku2** [comment]
Storing RefreshToken in browser (Cookie or Local Storage) is not a good practice from security point of view and should not be considered secure in any context.

**Comment by ottokruse** [comment]
It is Amplify that stores the refresh token in Local Storage.

Closing this one in favor of an existing Amplify issue: https://github.com/aws-amplify/amplify-js/issues/3436
