### ISSUE TITLE
Allow code to be used for more than three minutes?

### ISSUE THREAD

**Issue by martinpllu** [aws-samples/amazon-cognito-passwordless-email-auth#37]
Hi, thanks for this very useful example. 

We find that some users struggle to get the code from their email within three minutes, so we'd like codes to be valid for longer, perhaps for up to ten minutes.

Unfortunately we can't see any configuration options in Cognito to allow us to do this.

Do you know if this is possible?

**Comment by ottokruse** [comment]
AFAIK that is indeed not possible.

**Comment by ottokruse** [comment]
I guess if you want to get hands dirty you can work around it, by sending in an empty or "dummy" passcode (rough idea, not tested).

That would count as a wrong code of course (2 wrong codes allowed by the solution sample here) but will buy you another 3 minutes. You could make it so that supplying eg an empty or "dummy" code does not even increment the wrong code counter, so the user can search his inbox indefinitely.

Your web app implementation should then send that "dummy" code automatically after eg 2min en 50 secs. Note that if the web browser is no longer the front active window, triggers such as setTimeout/setInterval might be suspended, effectively making it hard to implement this work around.

Feel free to ignore this rough idea if you're not interested in coding/experimenting, just trying to offer an option might you really want one.

**Comment by martinpllu** [comment]
Hi Otto, the 'wrong code' approach is a great suggestion for a workaround. Thanks, we'll try that. Appreciate your help.
